name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest  
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies (npm)
        run: npm install
      - name: Lint (hbs)
        run: npm run lint:hbs
      - name: Lint (js)
        run: npm run lint:js
      - name: Run test
        run: npm run test
